[config]
model = "gemini/gemini-2.0-flash"
fallback_models = ["gemini/gemini-1.5-pro"]
ai_provider = "google"

[pr_reviewer]
extra_instructions = "Please use Japanese."

[pr_description]
generate_ai_title = true
extra_instructions = "Please use Japanese."

[pr_code_suggestions]
extra_instructions = "Please use Japanese."
